#!/usr/bin/env python3
"""Regenerate packs/short.js and packs/full.js from the curated Insults.xlsx.

Usage:  python3 scripts/xlsx-to-pack.py path/to/Insults.xlsx
Needs:  pip install openpyxl

Sheet "full":  column A = every adjective, column D = every noun.
Sheet "short": three static columns (Column 1 / 2 / 3), header in row 1; all 66 rows are canonical.
Regenerating overwrites the pack files, so keep hand edits in the spreadsheet.
"""
import json
import sys
from pathlib import Path

import openpyxl


WORDS_CREDIT = "Words drawn from various sources."  # the source spreadsheet and PDF name no word sources
WORDS_LICENSE = "Public domain"  # per the project owner


def js_list(words, indent="      "):
    items = [json.dumps(w, ensure_ascii=False) for w in words]
    lines = [", ".join(items[i:i + 6]) for i in range(0, len(items), 6)]
    return "[\n" + ",\n".join(indent + "  " + ln for ln in lines) + ",\n" + indent + "]"


def write_pack(path, pack_id, name, pools, columns):
    body = ",\n".join(f'    {json.dumps(k)}: {js_list(v)}' for k, v in pools.items())
    path.write_text(
        "// Generated by scripts/xlsx-to-pack.py from Insults.xlsx.\n"
        "// This file IS the word bank: edit it by hand to adapt the game (regenerating overwrites it).\n"
        "InsultGame.registerPack({\n"
        f"  id: {json.dumps(pack_id)},\n"
        f'  meta: {{ name: {json.dumps(name)}, credit: {json.dumps(WORDS_CREDIT)}, license: {json.dumps(WORDS_LICENSE)} }},\n'
        '  prefix: "Thou",\n'
        "  pools: {\n" + body + ",\n  },\n"
        f"  columns: {json.dumps(columns)},\n"
        "});\n",
        encoding="utf-8",
    )


def main(xlsx):
    wb = openpyxl.load_workbook(xlsx)
    out = Path(__file__).resolve().parent.parent / "packs"
    out.mkdir(exist_ok=True)

    full = [r for r in wb["full"].iter_rows(min_row=2, values_only=True)]
    adjectives = [r[0].strip() for r in full if r[0]]
    nouns = [r[3].strip() for r in full if r[3]]
    write_pack(out / "full.js", "full", f"Full list ({len(adjectives)} adjectives, {len(nouns)} nouns)",
               {"adjectives": adjectives, "nouns": nouns}, ["adjectives", "adjectives", "nouns"])

    rows = [r for r in wb["short"].iter_rows(min_row=2, values_only=True) if any(r)]
    cols = [[r[i].strip() for r in rows if r[i]] for i in range(3)]
    write_pack(out / "short.js", "short", f"Short list ({len(cols[0])} words per column)",
               {"column1": cols[0], "column2": cols[1], "column3": cols[2]},
               ["column1", "column2", "column3"])
    print(f"Wrote {out / 'full.js'} and {out / 'short.js'}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
